- name: default values
  hosts: localhost
  tasks:
  - name: Print default values
    ansible.builtin.debug:
      msg: "Hello {{ Course | default('Ansible')}}"

- name: Upper Case
  hosts: localhost
  vars:
    greeting: "Hello, Good Moring"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, Good Moring"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    number: [1, 2, 3, 4, 5, 6, 2, 4, 3, 5, 5] 
  tasks:
  - name: remove duplicate
    ansible.builtin.debug:
      msg: "{{ number | unique }}"     

- name: Print Min and Max
  hosts: localhost
  vars:
    ages: [22, 43, 45, 65, 77, 99]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "min age: {{ ages | min}}, max age: {{ ages | max }}"    

- name: Convert Dictionary into items/list
  hosts: localhost
  vars:
    my_dict: # This is called as dictionary or map or key/values pairs.
    Course: Ansible
    Trainer: SivaKumar
    Duration: 120hr
  tasks:
  - name: befor convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"           
  - name: after convert
    ansible.builtin.debug:
      msg: "after convert: {{ my_dict }}"         
