- name: default values
  hosts: localhost
  tasks:
  - name: Print default values
    ansible.builtin.debug:
      msg: "Hello {{ Course | default('Ansible')}}"

- name: Upper Case
  hosts: localhost
  vars:
    greeting: "Hello, Good Moring"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, Good Moring"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"  
